# fly.toml app configuration file generated for nisshi on 2023-09-22T15:57:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nisshi"
primary_region = "sin"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "node /app/build/ace migration:run --force"
