# fly.toml app configuration file generated for nisshi on 2023-09-24T10:22:18+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nisshi"
primary_region = "sin"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]

[env]
  DB_CONNECTION = "sqlite"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
